@startuml ClientUMLlist

title Client 'list' request

actor Client as Client
database Server as Server
Client -[#Black]> Client : Start Client
Server -[#Black]> Server : Start Server
note right
The server starts with ip 127.0.0.1 and port 4444.
end note
Client -[#Blue]> Server : UDP encoded in UTF-8
note left
The client send the string "list" to 
127.0.0.1 with port 4444.
end note
Server -[#Black]> Server : Get the directory
note right
The server generates a list[str] with all the filenames and convert to str.
end note
Client <[#Blue]- Server : UDP encoded in UTF-8
note right
The server send the list in a string format, encoded in UTF-8.
end note
Server -[#Black]> Server : End the process
Client -[#Black]> Client : Print list and end the process

@enduml